name: chroma_kit
description: A professional Flutter toolkit for color manipulation, accessibility, theme generation, blending, Material palettes, and color utilities.
version: 1.2.0
repository: https://github.com/Satyam-Gawali/chroma_kit

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true